### ISSUE TITLE
Unable to get FPS information on console

### ISSUE THREAD

**Issue by NowreenShaik** [xactai/SCALPR-01.5#11]
When we run the videos with respect to config file, we are unable to get the frames per sec (FPS) information on console.
![Screenshot_FPS](https://github.com/xactai/SCALPR-01.5/assets/152860323/ae160086-e402-460c-b4b8-aecfc18f72bf)

**Comment by Qengineering** [comment]
I print the latency time. It may give you better insight in how fast your system is. (The FPS is mainly determined by the video frame rate). If you like, I can always alter it back to FPS.

**Comment by NowreenShaik** [comment]
If you can print both it would be helpful.



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Qengineering** [comment]
I restored the FPS printing as it was before

**Comment by NowreenShaik** [comment]
Now able to get FPS on video

![fpsOnGamdias](https://github.com/xactai/SCALPR-01.5/assets/152860323/0ee34ef7-5764-4032-ba6e-c666a5cc49d4)
