### ISSUE TITLE
Program Display's only one Camera Feed

### ISSUE THREAD

**Issue by InternsXinthe** [xactai/SCALPR-01.5#2]
Hi @Qengineering 

we are trying to run the SCALPR_1.5 with the latest updates. But the program runs with only one Camera Feed and  it is not taking the video input also. Could you please check and clear this issue

config with 2 IMOU:

![with 2 Imou-1](https://github.com/xactai/SCALPR-01.5/assets/122441769/a3599753-c720-47b1-947f-58f36fbc9949)
![with 2 Imou-2](https://github.com/xactai/SCALPR-01.5/assets/122441769/48e79299-4d8d-4094-a15e-75441dd2128c)

config with video:

![with video](https://github.com/xactai/SCALPR-01.5/assets/122441769/f1019663-9246-4a32-bf2a-5a189ddfcb1a)

**Comment by Qengineering** [comment]
@InternsXinthe ,

You need to define the video source in the field `VIDEO_INPUT`. Here it is using the IMOU camera
```json
    "STREAM_2": {
        "CAM_NAME": "Cam 2",
        "MJPEG_PORT": 8092,
        "MQTT_TOPIC": "parking",
        "VIDEO_INPUT": "IMOU",
        "VIDEO_INPUTS_PARAMS": {
            "video": "./Nov_2min_30fps.mp4",
            "IMOU": "rtsp://admin:L239A796@192.168.178.39:554/cam/realmonitor?channel=1&subtype=0"
        },
```
And this one is playing a mp4 video
```json
    "STREAM_1": {
        "CAM_NAME": "Cam 1",
        "MJPEG_PORT": 8091,
        "MQTT_TOPIC": "parking",
        "VIDEO_INPUT": "video",
        "VIDEO_INPUTS_PARAMS": {
            "video": "./Nov_2min_30fps.mp4",
            "IMOU": "rtsp://admin:L239A796@192.168.178.39:554/cam/realmonitor?channel=1&subtype=0"
        },
```
The screenshots indicate that you have `IMOU` selected. Hence the error messages

**Comment by InternsXinthe** [comment]
@Qengineering 

i was tried with proper inputs for video.please check the 3rd screenshot

**Comment by Qengineering** [comment]
I'm sorry, but the third screenshot shows one video input and one cctv (IMOU) input.
At the office here, no problem.

 If you have any problems, try to run the streams one by one.
Firstly, see if the video work, not running the IMOU. Next, the other way around; only IMOU.
Then try to combine them.

**Comment by InternsXinthe** [comment]
@Qengineering ,

We ran the ALPR script in different modules as: 
1)1st input as SRK entry Cam and 2nd input as SRK Exit Cam  
2)1st input as SRK Exit Cam  and 2nd input as SRK ENTRY CAM.
3)1st input as SRK Exit Cam and 2nd input as video footage.
4)1st input as video and 2nd input as SRK ENTRY CAM.

While ran the script, we had faced the occurrences with the exit camera where ever placed in the script.
We didn't have any concern with SRK entry camera. Even though the resolution of both entry and exit cameras are same, but not getting results with exit camera.

We also tries with other camera too,instead of exit camera, but no luck same error occurred.

Please do suggest to overcome this and have good signs.

**Comment by InternsXinthe** [comment]
Tried with the latest code still facing the same issue

**Comment by Qengineering** [comment]
Your error is not code-related, but GStream, pipe related. 
Somehow the GStreamer couldn't open the CCTV camera.
When you look closely, you see that it is always a camera with IP 192.168.30.111 that does not work.

**Comment by InternsXinthe** [comment]
Actually, I tried with 2 other RTSP URLs all are working in VLC Player. But those two cameras are not working in SCALPR_1_5 Program

**Comment by Qengineering** [comment]
Hopefully solved the problem.
I use NVIDIA pipeline elements to get full profit from the CUDA architecture.
However, it doesn't work well with the composed RTSP commands of the ONVIF cameras.
For now, I disable the NVIDIA elements and use only GStreamer. (The one used in ALPR_1.0).
It has to be investigated further. NVIDIA has dedicated GPU elements decoding H264 (https://developer.nvidia.com/video-codec-sdk) and (https://docs.nvidia.com/video-technologies/video-codec-sdk/10.0/pdf/NVDEC_VideoDecoder_API_ProgGuide.pdf). Not sure how many streams it can process simultaneously.

**Comment by Qengineering** [comment]
Solved
