### ISSUE TITLE
Got Some core-dumped and Portal-border-corrupted issues 

### ISSUE THREAD

**Issue by InternsXinthe** [xactai/SCALPR-01.5#3]
Hi @Qengineering 

 
While Running the SCALPR_1.5 getting some core-dumped and Portal-border-corrupted issues.

In live CCTV stream of 1 camera, with 'trigger=wall', 'show birds-eye-view = true' many 4-wheelers are getting missed - maybe the system is calibrating and getting into some issues.Please check the attached screenshots for more details

portal-borders-corrupted-2023-10-11-16-03-38:

![portal-borders-corrupted-2023-10-11-16-03-38](https://github.com/xactai/SCALPR-01.5/assets/122441769/20397955-48b0-4f03-b1d1-405d308adf01)

core-dumped-portal-borders-corrupted-2023-10-11-16-04-21:

![core-dumped-portal-borders-corrupted-2023-10-11-16-04-21](https://github.com/xactai/SCALPR-01.5/assets/122441769/9247b175-7b53-483c-8e3f-0d8400e0edb0)

**Comment by Qengineering** [comment]
Your portal is still adapting to your local situation.
You can see it in the line `Portal is closing, Still 30 cars to go`
If you have defined
```json
    "PORTAL_FREEZE": 30,
```
you know it is in its early stage of adapting. Please give it some time.

**Comment by Qengineering** [comment]
BTW Your corrupted message indicates: `No file found`. In this case the defaults are loading

**Comment by Qengineering** [comment]
Solved
