### ISSUE TITLE
Some Trivial Enhancements for Color

### ISSUE THREAD

**Issue by InternsXinthe** [xactai/SCALPR-01.5#4]
Hi @Qengineering 

We ran the SCALPR_1_5 latest code and compared the MQTT information with your output file (output_color_novotel-9-11-2023.txt.txt). So we found that color detection is matched 100% with your output file and we have some enhancements 

1. In the MQTT, we want to see 'grey', instead of 'gray'
2. In the MQTT, we want to see 'toc_seen' (or time-of-color seen) which is the timestamp at which the color algorithm is applied

[output_color_novotel-10-11-23_xinthe.txt](https://github.com/xactai/SCALPR-01.5/files/13317373/output_color_novotel-10-11-23_xinthe.txt)
[difference.txt](https://github.com/xactai/SCALPR-01.5/files/13317374/difference.txt)

**Comment by Qengineering** [comment]
Done
