### ISSUE TITLE
CamelCase and uniform to* fields

### ISSUE THREAD

**Issue by Ramesh-Kesunukurthi** [xactai/SCALPR-01.5#5]
@Qengineering 

Please find the below required changes

To make some fields uniform -
1) tos_seen = tot_seen or time-of-tracking or time at which we started tracking
2) toi_seen = time-of-inspection or time at which we marked the vehicle as inspected
3) too_seen = time-of-ocr or time at which OCR was done (based on Rients-Intelligence)
4) toc_seen = time-of-color or time at which color was finalized

All to*_seen start from 00:00

Note: Please make sure the Json output keys should be camel case

**Comment by Qengineering** [comment]
Done

**Comment by NowreenShaik** [comment]
@Qengineering 

Please print Json output keys in camelCase. 

Please find the below code as reference.

MQTTMessageArrived
	topic:
    message:{
	 "version":
	 "camId":
	 "frameId":
	 "vehicleDetails":[
			 "vehicleId":
			 "vehicleType":
			 "firstSeen":
			 "lastSeen":
			 "licensePlateText":
			 "vehicleColor":
			 "isInspected":
			 "tos":
			 "toi":
			 "doi":
			 "too":
			 "toc":
			 "dov":
	]

}

**Comment by Qengineering** [comment]
Done

**Comment by NowreenShaik** [comment]
Now printing Json output keys in camelCase. Thanks
