### ISSUE TITLE
Add attributes to the JSON output 

### ISSUE THREAD

**Issue by Ramesh-Kesunukurthi** [xactai/SCALPR-01.5#6]
@Qengineering 

Please find the below required Enhancements

Add the attributes to the JSON output from SCALPR

How much of time the car is waiting for inspection ( later can be used for checking valet wait time).

**Comment by Qengineering** [comment]
Done

**Comment by Ramesh-Kesunukurthi** [comment]
@Qengineering 

Please find the below required Enhancements

(Start time 00:00 - Time at which the car is first detected. This is not an attribute. But reference to below values)

tos = Time at which we started tracking the car - (mm:ss)
toi = Time a sentry start inspecting the car - (mm:ss)
doi = Duration of inspection of car by sentry - (in Seconds)
too = Time at which OCR was done (Best license image).Because we are track the color at side of the car - (mm:ss)
toc = Time-of-color or time at which color was finalized - (mm:ss)
