### ISSUE TITLE
Run SCALPR with configuration file as a command-line parameter

### ISSUE THREAD

**Issue by abdul-xinthe** [xactai/SCALPR-01.5#8]
Instead of embedding the application configuration file directly within the program's code, send it as a command-line parameter to the application.

ex: '$scalpr1.5 -c .../path/.../config-novotel-IN-2-minutes.json'

**Comment by Qengineering** [comment]
Now you have (optional) command line arguments.

**Comment by NowreenShaik** [comment]
Tried running SCALPR with configuration file as a command line parameter but not working

**Comment by NowreenShaik** [comment]
Now we can run SCALPR with configuration file as command line parameter

![SCALPR-With-ConfigFile-As-Command-Line-Parameter](https://github.com/xactai/SCALPR-01.5/assets/152860323/2842f4f2-31b7-4fda-9a92-3ca9df5982fd)
